version: "3.9"
services:
  cali_housing_inference_util:
    container_name: cali_housing_inference_util
    image: local/highwind-examples/cali-housing-inference:latest
    platform: linux/amd64
    command: --model_name=model
    working_dir: /app
    ports:
      - "8080:8080"