version: "3.9"
services:
  iris_inference_util:
    container_name: iris_inference_util
    image: local/highwind-examples/iris-inference:latest
    command: --model_name=model
    working_dir: /app
    ports:
      - "8080:8080"